# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: diagnostic.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'diagnostic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64iagnostic.proto\x12\ndiagnostic\"a\n\nDiagnostic\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\x05\x12&\n\x08severity\x18\x03 \x01(\x0e\x32\x14.diagnostic.Severity\x12\x0f\n\x07message\x18\x04 \x01(\t\"3\n\x11\x44iagnosticRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x10\n\x08\x63ontents\x18\x02 \x01(\t\"A\n\x12\x44iagnosticResponse\x12+\n\x0b\x64iagnostics\x18\x01 \x03(\x0b\x32\x16.diagnostic.Diagnostic*9\n\x08Severity\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x0b\n\x07WARNING\x10\x02\x12\x08\n\x04INFO\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'diagnostic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEVERITY']._serialized_start=251
  _globals['_SEVERITY']._serialized_end=308
  _globals['_DIAGNOSTIC']._serialized_start=32
  _globals['_DIAGNOSTIC']._serialized_end=129
  _globals['_DIAGNOSTICREQUEST']._serialized_start=131
  _globals['_DIAGNOSTICREQUEST']._serialized_end=182
  _globals['_DIAGNOSTICRESPONSE']._serialized_start=184
  _globals['_DIAGNOSTICRESPONSE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
